server:
  port: 8761 # default port for Eureka server.


eureka:
  client:
    register-with-eureka: false # since this is the server we don't
    fetch-registry: false       # want to register it to itself